### ISSUE TITLE
【问题反馈】这几天打卡提示自动打卡出错

### ISSUE THREAD

**Issue by xiaochen-0** [XiaoMiku01/bili-live-heart#10]
au您好，这几天我的打卡总会出错，其他功能（获取小心心、给指定主播送礼物、签到）正常，云函数日志如下：
【前略】
Server酱已推送

直播区签到成功(本月签到天数：7/31)

赠送了27个小心心，2个辣条

自动打卡出错：WebApiRequestError('',)

complete!

Response RequestId:b6ca6b2e-af0a-4446-bcf0-4274d7b8e23f RetMsg:true

END RequestId:b6ca6b2e-af0a-4446-bcf0-4274d7b8e23f

Report RequestId:b6ca6b2e-af0a-4446-bcf0-4274d7b8e23f Duration:322992ms Memory:128MB MemUsage:32.117188MB

server酱推送如下：
![微信图片_20211207202450](https://user-images.githubusercontent.com/68267854/145028665-f742b6af-a9cb-40d0-9b2c-ea1128e38001.jpg)

请问如何解决呢，谢谢您！

**Comment by XiaoMiku01** [comment]
已更新，重新下载部署0.7.0压缩包

**Comment by xiaochen-0** [comment]
> 

好的，谢谢！
