### ISSUE TITLE
为什么我ruid的值设置成0好像还是会送出小心心啊

### ISSUE THREAD

**Issue by ZackRegex** [XiaoMiku01/bili-live-heart#12]
如题，背包里的小心心并没有增加，好像随得随送出去了

还有ruid能设置多个UID吗，刚开始设置了一堆发现报错，试了半天才明白只能设置一个值=.=
完成任务后的报告能输出所有牌子的吗，现在只有一个牌子的报告

**Comment by XiaoMiku01** [comment]
看清楚文档，我写的很清楚，只显示一个

**Comment by ZackRegex** [comment]
懂了，设置0没有问题，背包里拿到24个了
感谢大佬的程序  (b ᵔ▽ᵔ)b
