### ISSUE TITLE
可以增加控制睡眠时间的环境变量吗

### ISSUE THREAD

**Issue by Astesai** [XiaoMiku01/bili-live-heart#15]
60秒有点长

**Comment by XiaoMiku01** [comment]
你说的哪个60秒？

**Comment by Astesai** [comment]
> 你说的哪个60秒？

是捏

**Comment by XiaoMiku01** [comment]
> > 你说的哪个60秒？
> 
> 是捏

哪里的60秒？？（你为什么不看直播？）

**Comment by Astesai** [comment]
> > > 你说的哪个60秒？
> > 
> > 
> > 是捏
> 
> 哪里的60秒？？（你为什么不看直播？）

60秒后发送第233个xxx号直播间内心跳（在看了）

**Comment by XiaoMiku01** [comment]
> 

那是B站规定的心跳间隔，改不了
