### ISSUE TITLE
不知道能不能按这个逻辑运行

### ISSUE THREAD

**Issue by Astesai** [XiaoMiku01/bili-live-heart#17]
先检测今天是否送完了24颗心或者包里有没有24颗心，如果没有才开始获取

**Comment by chenyl0426** [comment]
直播间挂机助手那边作者说，这个检测比较困难。其实如果在用同类软件/脚本的话只保留一个不就好了？

**Comment by Astesai** [comment]
就是不想一直开电脑才用你的挂云函数

**Comment by chenyl0426** [comment]
> 就是不想一直开电脑才用你的挂云函数

我不是开发者啦……你都用了云函数了，那每天的24个小心心给云函数接管了自动送掉，其它有同类功能的全关了就行啊。还是说你不想送给同一个人？

**Comment by Astesai** [comment]
> > 就是不想一直开电脑才用你的挂云函数
> 
> 我不是开发者啦……你都用了云函数了，那每天的24个小心心给云函数接管了自动送掉，其它有同类功能的全关了就行啊。还是说你不想送给同一个人？

之前急着出门没留意看id🤣
因为我还有个小号要跑，勋章不满足条件不能用云函数，本地跑又太慢了😢

**Comment by XiaoMiku01** [comment]
> > > 就是不想一直开电脑才用你的挂云函数
> > 
> > 
> > 我不是开发者啦……你都用了云函数了，那每天的24个小心心给云函数接管了自动送掉，其它有同类功能的全关了就行啊。还是说你不想送给同一个人？
> 
> 之前急着出门没留意看id🤣 因为我还有个小号要跑，勋章不满足条件不能用云函数，本地跑又太慢了😢

解决方法：创建函数时，把高级选项里的【异步执行】打开，然后回到上面【超时时间】填到最大，能突破15分钟，不过如果你要是没有9个粉丝牌，就把index.py 第17行的 cloud_service=True 改成  cloud_service=False

**Comment by Astesai** [comment]
> 

好的 谢谢解答
