### ISSUE TITLE
最后一步运行出错:KeyError('LIVE_BUVID') 请教下

### ISSUE THREAD

**Issue by Rango-Wu** [XiaoMiku01/bili-live-heart#18]
C:\Python39\Lib\site-packages\bili-live-heart-master>python index.py
start!
运行出错:KeyError('LIVE_BUVID')

cookie也查了好几次

**Comment by Rango-Wu** [comment]
最后用webHeartBeat?hb=数据包里的cookie运行成功
HeartBeat包cookie依旧不行 麻烦大佬解答下

**Comment by Rango-Wu** [comment]
运行了两次最后结果亲密度1302 不知什么问题

**Comment by XiaoMiku01** [comment]
24个小心心加俩个辣条就是1302
