### ISSUE TITLE
赠送礼物失败时，后续执行与消息推送出错

### ISSUE THREAD

**Issue by wangzy77** [XiaoMiku01/bili-live-heart#19]
你好，我发现了一个稀有的问题：当小心心任务完成后，如果给ruid送礼物失败，则后续代码都被跳过，直接开始推送消息，而且消息内容缺失严重。如下为问题出现时的执行日志与推送截图
```
...
第5个xxx号直播间内心跳已发送（用户：xxx）
获得第24个小心心（用户：xxx）
60秒后发送第6个xxx号直播间内心跳（用户：xxx）
今天小心心任务已完成（用户：xxx）
Server酱已推送

出错日志：
今日已签到过,无法重复签到
自动打卡出错：WebApiRequestError('该房间已被锁定,无法收礼哦～',)
complete!
...
```

> ![1](https://user-images.githubusercontent.com/14155555/147472022-f32a052e-2603-45b5-85cf-6da8e593274b.png)

图2为我修改ruid后执行成功的推送截图。与图1对比，可见当错误发生时，自动打卡步骤被跳过

> ![2](https://user-images.githubusercontent.com/14155555/147472044-998694ab-1d50-4139-a2fc-0960b75bf6a1.png)

请问可否修改成当赠送礼物失败时，跳过该步骤，继续执行后续自动打卡等步骤呢？Thanks♪(･ω･)ﾉ

**Comment by XiaoMiku01** [comment]
无法送礼物的房间我还是第一次见，属实没考虑到，单独为这个更新版本感觉没必要。。。

**Comment by wangzy77** [comment]
房间被封了就送不了礼物，罕见的问题。不妨合并到下个大版本

**Comment by EmiliasamaEMT** [comment]
我没有设置ruid，但是有一个房间是被禁言的，也无法进行自动打卡

**Comment by XiaoMiku01** [comment]
新版本 已添加礼物赠送失败的日志
