### ISSUE TITLE
运行出错:KeyError('roomid')

### ISSUE THREAD

**Issue by WendaoLee** [XiaoMiku01/bili-live-heart#2]
已git获取最新版本源码，更新之后出现这个问题
user.toml配置如下：
![截图](https://sharedmemories-1301733002.cos.ap-shanghai.myqcloud.com/memory/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-11-11%20141245.jpg)

**Comment by XiaoMiku01** [comment]
运行到了哪一步停了

**Comment by WendaoLee** [comment]
> 运行到了哪一步停了

控制台消息“检测到是本地模式……正在开始”那个地方停止的。

**Comment by XiaoMiku01** [comment]
b站私信我 https://space.bilibili.com/32957695 ，cookie发我，我来调试一下，可能是关注的房间有点特殊

**Comment by WendaoLee** [comment]
问题排查原因：存在没有直播间的UP主的牌子。
最简单解决方法：删牌子。

**Comment by XiaoMiku01** [comment]
已修复，目前无需删牌子
