### ISSUE TITLE
启动时错误 运行出错:RuntimeError('SSL is not supported.')

### ISSUE THREAD

**Issue by NishikiAsumi7** [XiaoMiku01/bili-live-heart#20]
终端Log
[root@iZ8v bili-live-heart]# python3 index.py
start!
检测到为本地运行模式
开始今天的小心心任务（用户：）
运行出错:RuntimeError('SSL is not supported.')

系统版本 centOS 7.9
Python 3.8.6

**Comment by XiaoMiku01** [comment]
似乎是你的环境问题
