### ISSUE TITLE
运行出错:WebApiRequestError('用户不存在',)

### ISSUE THREAD

**Issue by wr786** [XiaoMiku01/bili-live-heart#21]
```
start!
检测到为云函数模式
开始今天的小心心任务（用户：             ）
运行出错:WebApiRequestError('用户不存在',)
```

疑似是获取粉丝勋章列表api出问题

**Comment by lxhlight** [comment]
### 这个是临时的解决办法，更好的方案请等待该项目作者给出

1.url 换为 'https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals'
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L144
2.改为 `'page_size': page_size, `
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L148
3.改为 `page_info = data['page_info']`
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L36
4.改为 `assert page == page_info['cur_page']`
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L37
5.改为 `for medal in data['items']:`
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39
6.改为 `if page < page_info['total_page']:`
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L42
**可以直接在云函数的配置页面里的api.py和run.py中修改**
![在线编辑](https://user-images.githubusercontent.com/49703499/147858312-d1479b78-4f1e-4578-b605-a75203f25577.jpg) 
**调用成功了捏，嘿嘿嘿😋**
![Snipaste_2022-01-02_03-22-51](https://user-images.githubusercontent.com/49703499/147858600-43f7ffa3-bd8c-4aaf-9481-5b9ce37201fc.jpg)

**Comment by Asoul-Dianava** [comment]
您

**Comment by XiaoMiku01** [comment]
> ### 这个是临时的解决办法，更好的方案请等待该项目作者给出
> 1.url 换为 'https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals'
> 
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L144
> 
> 
> 2.改为 `'page_size': page_size, `
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L148
> 
> 
> 3.改为 `page_info = data['page_info']`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L36
> 
> 
> 4.改为 `assert page == page_info['cur_page']`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L37
> 
> 
> 5.改为 `for medal in data['items']:`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39
> 
> 
> 6.改为 `if page < page_info['total_page']:`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L42
> 
> 
> **可以直接在云函数的配置页面里的api.py和run.py中修改**
> ![在线编辑](https://user-images.githubusercontent.com/49703499/147858312-d1479b78-4f1e-4578-b605-a75203f25577.jpg)
> **调用成功了捏，嘿嘿嘿🤭**
> ![Snipaste_2022-01-02_03-22-51](https://user-images.githubusercontent.com/49703499/147858600-43f7ffa3-bd8c-4aaf-9481-5b9ce37201fc.jpg)

感谢，我还在期末考试，解决方案昨晚就写了，没时间同步

**Comment by ZhangBowen** [comment]
> ### 这个是临时的解决办法，更好的方案请等待该项目作者给出
> 1.url 换为 'https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals'
> 
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L144
> 
> 
> 2.改为 `'page_size': page_size, `
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L148
> 
> 
> 3.改为 `page_info = data['page_info']`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L36
> 
> 
> 4.改为 `assert page == page_info['cur_page']`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L37
> 
> 
> 5.改为 `for medal in data['items']:`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39
> 
> 
> 6.改为 `if page < page_info['total_page']:`
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L42
> 
> 
> **可以直接在云函数的配置页面里的api.py和run.py中修改**
> ![在线编辑](https://user-images.githubusercontent.com/49703499/147858312-d1479b78-4f1e-4578-b605-a75203f25577.jpg)
> **调用成功了捏，嘿嘿嘿🤭**
> ![Snipaste_2022-01-02_03-22-51](https://user-images.githubusercontent.com/49703499/147858600-43f7ffa3-bd8c-4aaf-9481-5b9ce37201fc.jpg)

我照着这个修正修改后运行有新的报错：
运行出错:WebApiRequestError("Key: 'GetInfoByRoomReq.RoomId' Error:Field validation for 'RoomId' failed on the 'required' tag",)

**Comment by Karlex1337** [comment]
运行出错:AssertionError()

Response RequestId:ab987731-58e8-4eaf-b5ca-786ca2030ebf RetMsg:false

END RequestId:ab987731-58e8-4eaf-b5ca-786ca2030ebf

Report RequestId:ab987731-58e8-4eaf-b5ca-786ca2030ebf Duration:121ms Memory:128MB MemUsage:23.546188MB


怎么会是😰

**Comment by A-Soul-Kira** [comment]
谢谢，已解决

**Comment by Karlex1337** [comment]
> 谢谢，已解决

把zip包发我一下，我手机改的好像不对

**Comment by A-Soul-Kira** [comment]
> 
[bili-live-heart_cloud0.7.0.zip](https://github.com/XiaoMiku01/bili-live-heart/files/7798558/bili-live-heart_cloud0.7.0.zip)

**Comment by Karlex1337** [comment]
> > 
> 
> [bili-live-heart_cloud0.7.0.zip](https://github.com/XiaoMiku01/bili-live-heart/files/7798558/bili-live-heart_cloud0.7.0.zip)

额这个是原来的吧

**Comment by A-Soul-Kira** [comment]
[new.zip](https://github.com/XiaoMiku01/bili-live-heart/files/7798563/new.zip)
换好了

**Comment by ZhangBowen** [comment]
> > ### 这个是临时的解决办法，更好的方案请等待该项目作者给出
> > 1.url 换为 'https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals'
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L144
> > 
> > 2.改为 `'page_size': page_size, `
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L148
> > 
> > 3.改为 `page_info = data['page_info']`
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L36
> > 
> > 4.改为 `assert page == page_info['cur_page']`
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L37
> > 
> > 5.改为 `for medal in data['items']:`
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39
> > 
> > 6.改为 `if page < page_info['total_page']:`
> > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L42
> > 
> > **可以直接在云函数的配置页面里的api.py和run.py中修改**
> > ![在线编辑](https://user-images.githubusercontent.com/49703499/147858312-d1479b78-4f1e-4578-b605-a75203f25577.jpg)
> > **调用成功了捏，嘿嘿嘿🤭**
> > ![Snipaste_2022-01-02_03-22-51](https://user-images.githubusercontent.com/49703499/147858600-43f7ffa3-bd8c-4aaf-9481-5b9ce37201fc.jpg)
> 
> 我照着这个修正修改后运行有新的报错： 运行出错:WebApiRequestError("Key: 'GetInfoByRoomReq.RoomId' Error:Field validation for 'RoomId' failed on the 'required' tag",)

找到问题了，因为我有一些没有直播间的up的粉丝牌，在run.py的L118行后面加一个判断把这些滤掉就好了
if m['roomid'] == 0:
    continue

https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L118

@Karlex1337 看看这个能不能解决你的问题
cc @XiaoMiku01

**Comment by ZhangBowen** [comment]
> > > ### 这个是临时的解决办法，更好的方案请等待该项目作者给出
> > > 1.url 换为 'https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals'
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L144
> > > 
> > > 2.改为 `'page_size': page_size, `
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/api.py#L148
> > > 
> > > 3.改为 `page_info = data['page_info']`
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L36
> > > 
> > > 4.改为 `assert page == page_info['cur_page']`
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L37
> > > 
> > > 5.改为 `for medal in data['items']:`
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39
> > > 
> > > 6.改为 `if page < page_info['total_page']:`
> > > https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L42
> > > 
> > > **可以直接在云函数的配置页面里的api.py和run.py中修改**
> > > ![在线编辑](https://user-images.githubusercontent.com/49703499/147858312-d1479b78-4f1e-4578-b605-a75203f25577.jpg)
> > > **调用成功了捏，嘿嘿嘿🤭**
> > > ![Snipaste_2022-01-02_03-22-51](https://user-images.githubusercontent.com/49703499/147858600-43f7ffa3-bd8c-4aaf-9481-5b9ce37201fc.jpg)
> > 
> > 
> > 我照着这个修正修改后运行有新的报错： 运行出错:WebApiRequestError("Key: 'GetInfoByRoomReq.RoomId' Error:Field validation for 'RoomId' failed on the 'required' tag",)
> 
> 找到问题了，因为我有一些没有直播间的up的粉丝牌，在run.py的L118行后面加一个判断把这些滤掉就好了 if m['roomid'] == 0: continue
> 
> https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L118
> 
> @Karlex1337 看看这个能不能解决你的问题 cc @XiaoMiku01

后面还有个签到流程还是会出问题

可以在获取粉丝牌阶段直接过滤，方便点
把run.py的39~40行替换成
```py
for medal in data['items']:
    if medal['roomid'] == 0:
        continue
    yield medal
```
https://github.com/XiaoMiku01/bili-live-heart/blob/e6ea2948bd6badd1d19c8dfdd256ddf7d2e4b66d/run.py#L39

**Comment by XiaoMiku01** [comment]
已修复，帮忙测一下

**Comment by lxhlight** [comment]
> 已修复，帮忙测一下
可以用了捏😘
