### ISSUE TITLE
考虑添加TG推送和多账户功能吗

### ISSUE THREAD

**Issue by Asoul-Dianava** [XiaoMiku01/bili-live-heart#25]
或许可以参考https://github.com/y1ndan/onepush 和 https://github.com/ZainCheung/netease-cloud ？

**Comment by XiaoMiku01** [comment]
建议收到，目前正在重构代码

**Comment by Asoul-Dianava** [comment]
> 建议收到，目前正在重构代码

mua你一下

**Comment by XiaoMiku01** [comment]
国内环境TG不会支持，如有需要可以使用这个pr #27 不过将不会合并到主分支，目前dev-1.0.0 本地运行已支持多用户 腾讯遇难书可以复制函数改变环境变量用于多用户
