### ISSUE TITLE
!!!!推荐加个青龙教程虽然我已经用上了

### ISSUE THREAD

**Issue by liuruidong4** [XiaoMiku01/bili-live-heart#28]
青龙就是自动定时执行任务的
依赖就是库先装一下
我就是用青龙的加了
ql repo库拉一下
配置文件自己进去新建一下 (也省的定时更新拉的时候覆盖掉)
另一个py改一下配置文件名
然后另一个配置里写小号
直接挂两个号的说！！
加了青龙会有更多人用 需要教程罢了就是

**Comment by XiaoMiku01** [comment]
新版已经重构代码了，目前还在dev-1.0.0分支里，新版本内置定时模块，和支持多账号运行了，只需要挂在后台让程序自动运行即可 目前还在写文档，近期会合并的

**Comment by liuruidong4** [comment]
> 新版已经重构代码了，目前还在dev-1.0.0分支里，新版本内置定时模块，和支持多账号运行了，只需要挂在后台让程序自动运行即可 目前还在写文档，近期会合并的

大佬牛皮~稳
