### ISSUE TITLE
云函数版本没有收到ServerChan的反馈

### ISSUE THREAD

**Issue by ringchelin** [XiaoMiku01/bili-live-heart#30]
在百度云下载的云函数压缩包，是最新的版本。其他使用都正常，但Sercer酱的推送没有收到QAQ。又测试了下，错误日志如下：
错误日志:

直播区签到失败: 今日已签到过,无法重复签到

背包里未发现小心心

Response RequestId:755abd6a-1701-4bf2-9ec5-8952744d2070 RetMsg:true

END RequestId:755abd6a-1701-4bf2-9ec5-8952744d2070

Report RequestId:755abd6a-1701-4bf2-9ec5-8952744d2070 Duration:69411ms Memory:128MB MemUsage:49.625343MB

**Comment by ringchelin** [comment]
还有个问题，执行日志里面如下：
开始小心心任务

Invalid room info: RoomInfo(room_id=5920513, parent_area_id=0, area_id=0, owner='小约翰可汗', ruid=23947287)

**Comment by XiaoMiku01** [comment]
B站私信我cookie,我来测试

**Comment by XiaoMiku01** [comment]
可能是你的环境变量的sendkey填错了吧，全小写
