### ISSUE TITLE
云函数测试后提示“登录失败,请`关闭`浏览器`无痕模式`重新抓取cookie后重试”

### ISSUE THREAD

**Issue by WoodAsh2501** [XiaoMiku01/bili-live-heart#32]
云函数测试后提示“登录失败,请`关闭`浏览器`无痕模式`重新抓取cookie后重试”

然而我并没有开无痕模式
浏览器 Microsoft Edge 版本 97.0.1072.55
cookie也是按照指南里的方法获取的

不知道是哪里有问题🤔感谢大佬解答了

**Comment by XiaoMiku01** [comment]
#31

**Comment by WoodAsh2501** [comment]
> #31

感谢！
