### ISSUE TITLE
每天第一次运行都会中断，第二次及以后才能正常运行

### ISSUE THREAD

**Issue by LMWC** [XiaoMiku01/bili-live-heart#33]
之前使用的一月二号的临时改动版本，可以每天一次正常运行
一月十一号更换为1.0.0版本后，每天第一次运行都会中断，第二次及以后才能正常运行，需要运行两次才能完成全部任务
每天第一次运行的日志有以下两个地方有问题：
①赠送小心心出错
![QQ截图20220113113613](https://user-images.githubusercontent.com/80448506/149261691-38fa7a34-0bed-4200-b3c3-0d1315142cb2.png)
②打卡部分直播间后出错
![QQ截图20220113113724](https://user-images.githubusercontent.com/80448506/149261774-a730a952-ddb7-4b90-948f-6760ced715ae.png)

**Comment by LMWC** [comment]
第二次运行日志就正常了
![QQ截图20220113114414](https://user-images.githubusercontent.com/80448506/149262375-02ee2762-a310-4d5d-8298-8df84bb94b80.png)
![QQ截图20220113114547](https://user-images.githubusercontent.com/80448506/149262382-134276a2-1a52-4b47-bba2-86d6bfd433ff.png)

**Comment by XiaoMiku01** [comment]
概率事件还是必然事件

**Comment by LMWC** [comment]
> 概率事件还是必然事件

我十一号下午部署测试没问题，设置的每天早上五点触发。但十二号和十三号都是五点自动触发后运行出现中断，然后我上午九十点再手动运行一遍才能完成所有任务。
之前月初的临时方案也是设置的上午五点触发，可以正常完成任务。

**Comment by XiaoMiku01** [comment]
> > 概率事件还是必然事件
> 
> 我十一号下午部署测试没问题，设置的每天早上五点触发。但十二号和十三号都是五点自动触发后运行出现中断，然后我上午九十点再手动运行一遍才能完成所有任务。 之前月初的临时方案也是设置的上午五点触发，可以正常完成任务。

可能由于个别房间被封禁导致的？

**Comment by LMWC** [comment]
> > > 概率事件还是必然事件
> > 
> > 
> > 我十一号下午部署测试没问题，设置的每天早上五点触发。但十二号和十三号都是五点自动触发后运行出现中断，然后我上午九十点再手动运行一遍才能完成所有任务。 之前月初的临时方案也是设置的上午五点触发，可以正常完成任务。
> 
> 可能由于个别房间被封禁导致的？

我有粉丝牌的直播间都没有被封禁，每天我都会在网页上检查是否所有直播间都打卡成功，有些直播间由于弹幕关键词屏蔽没能打卡成功的，我都会手动发弹幕1打卡补上

**Comment by XiaoMiku01** [comment]
你多少个牌子？这种bug排查难度有点大

**Comment by LMWC** [comment]
88个牌子
我暂时还是回滚到之前月初的版本

**Comment by XiaoMiku01** [comment]
v1.1.0 已修复，麻烦测试一下

**Comment by LMWC** [comment]
可以，问题解决了
