### ISSUE TITLE
获取粉丝牌直播间数据问题

### ISSUE THREAD

**Issue by NishikiAsumi7** [XiaoMiku01/bili-live-heart#38]
获取小心心的时候只会读取最大可用的直播间数量，导致后面弹幕打卡的时候没有打卡到所有的直播间。

举个例子，如果我有7个粉丝牌，开始任务之后进行打卡，在运行16分钟后因为某种原因被打断。那么我现在获取了21个小心心，还差3个到上限。重新尝试运行的时候只会打开三个直播间获取小心心，然后发弹幕打卡就会只进行这三个直播间的打卡然后结束。

看了一下源码，可能是获取粉丝牌对应直播间数据的逻辑放在了获取小心心的方法里面，弹幕打卡的时候直接读取的这一步获取到的数据。超过24个粉丝牌的部分会被忽略掉打卡，如果我今天看了直播已经获取了一部分小心心也可能会忽略更多的弹幕打卡。

**Comment by XiaoMiku01** [comment]
已经在v1.1.0解决这个问题了
