### ISSUE TITLE
功能建议#建议增加每日自动分享一个视频

### ISSUE THREAD

**Issue by chenyl0426** [XiaoMiku01/bili-live-heart#4]
功能建议#建议增加每日自动分享一个视频
![IMG_20211121_081407](https://user-images.githubusercontent.com/61819463/142744546-d93eecdc-dc45-47a3-abe2-a96516c334c9.jpg)

**Comment by XiaoMiku01** [comment]
不是本项目的功能，暂不考虑，同类脚本有很多
