### ISSUE TITLE
使用1.1.0版本仍然无法弹幕打卡全部粉丝牌直播间

### ISSUE THREAD

**Issue by Robotmaid** [XiaoMiku01/bili-live-heart#40]
![image](https://user-images.githubusercontent.com/50980729/154112479-2877c4ee-85c6-49d1-b7f6-df6f3702d159.png)
版本为最新的，但是只能打卡剩余小心心数的直播间

**Comment by Robotmaid** [comment]
我时间设置为每天00:10开始运行，当我在直播间看的时候只能打卡23个，不在直播间看的时候只能打卡24个

**Comment by Windrunner20** [comment]
> 我时间设置为每天00:10开始运行，当我在直播间看的时候只能打卡23个，不在直播间看的时候只能打卡24个
我的也是 只能23 24个 有的时候又能全部打卡

**Comment by Windrunner20** [comment]
> 我时间设置为每天00:10开始运行，当我在直播间看的时候只能打卡23个，不在直播间看的时候只能打卡24个

不过我刚才试了一下跑再跑一遍完成了 我打算试试每次跑两边 看看会不会好

**Comment by Robotmaid** [comment]
我是每次都是23,24，没有打全过
