### ISSUE TITLE
Server酱推送不正常

### ISSUE THREAD

**Issue by starrin** [XiaoMiku01/bili-live-heart#41]
用最新版本部署在群晖上的，日志中没有任何报错，但是Server酱推送消息不正确
![Screenshot_20220310_112054_com tencent mm](https://user-images.githubusercontent.com/62949447/157582373-3f79b21b-2e50-460a-b493-3ec4b57a9e18.jpg)
![Screenshot_20220310_112514](https://user-images.githubusercontent.com/62949447/157582531-1817b2e8-676e-484b-b5a1-28101e9b56eb.jpg)

**Comment by XiaoMiku01** [comment]
可能是某个粉丝牌的问题，可以的话B站死私信我cookie，我来排查一下

**Comment by starrin** [comment]
私信啦

**Comment by XiaoMiku01** [comment]
等看完直播

**Comment by starrin** [comment]
破案了，原来是因为我每天自动喂小心心的直播间开了舰长，送小心心不涨亲密度，导致统计时报错
谢谢大佬帮忙排查
我感觉这个还是可以加个提醒处理一下这种情况，毕竟这样报错还是不是太好
