### ISSUE TITLE
搞了一个 github action 的版本 (无需自架且完全免费)

### ISSUE THREAD

**Issue by eric2788** [XiaoMiku01/bili-live-heart#42]
因为看到函数云付费了来着，又想到 github action CI 支援 crontab schedule 触发, 所以 fork 了搞了个 github action 版本

https://github.com/eric2788/bili-live-heart

由于安全问题，所以改了不使用设定档案，改为传入参数

因为没有 Discussion 板块，所以放issue了......

**Comment by XiaoMiku01** [comment]
github action 滥用会导致仓库封禁 暂不考虑

**Comment by eric2788** [comment]
编辑：好像还真有这个限制，感谢提醒，已经删了

**Comment by eric2788** [comment]
@XiaoMiku01 https://developers.cloudflare.com/workers/platform/cron-triggers/ 你看看这个怎么样，如果再不行就算了
