### ISSUE TITLE
运行的好好的突然出错了

### ISSUE THREAD

**Issue by Moment0901** [XiaoMiku01/bili-live-heart#45]
Using selector: EpollSelector

检测到为云函数模式

Expecting value: line 1 column 1 (char 0)

Server酱已推送

Unclosed client session

client_session: <aiohttp.client.ClientSession object at 0x7f45d37060d0>

Unclosed connector

connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f45d4ae0440>, 2864.068163939)]']

connector: <aiohttp.connector.TCPConnector object at 0x7f45d3706450>

**Comment by XiaoMiku01** [comment]
全崩了，马上修

**Comment by Moment0901** [comment]
辛苦啦

**Comment by XiaoMiku01** [comment]
已修复
