### ISSUE TITLE
docker中出现SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/bili-live-heart#48]
如果设置的docker不带证书 就会出现SSL: CERTIFICATE_VERIFY_FAILED错误
在aiohttp.ClientSession()里添加connector=aiohttp.TCPConnector(verify_ssl=False)就可以解决
建议添加一下 我自己找了好半天才解决

**Comment by trytodupe** [comment]
一共有两处aiohttp.ClientSession()
一个是 push/serverchan.py 的13行
一个是 bili/login.py 的45行

**Comment by XiaoMiku01** [comment]
那是docker环境问题，不是脚本问题
