### ISSUE TITLE
血泪，建议加一个小心心赠送上限

### ISSUE THREAD

**Issue by AmakuraMio0017** [XiaoMiku01/bili-live-heart#5]
，试运行把送的80个小心心一天全给送了

赠送了80个小心心，2个辣条
40个房间打卡成功
目前：一个魂10级
今日亲密度：1500/1500

麻了QAQ！！！
一天最多50*28=1400+100=1500亲密度
所以超过28个小心心都是浪费的

**Comment by XiaoMiku01** [comment]
一个月前写的，根本没想到会送小心心

**Comment by AmakuraMio0017** [comment]
麻了2333333，辛苦了！明天测试一下小心心获取效果，如果可以五分钟解决就不用挂机了！
加油捏！

**Comment by AmakuraMio0017** [comment]
> 一个月前写的，根本没想到会送小心心

请教！
架设的服务有没有维护周期呢？
还是说不手动停下会一直持续运行下去

**Comment by XiaoMiku01** [comment]
啥意思？

**Comment by AmakuraMio0017** [comment]
> 啥意思？

就是说架设好的自动服务，是按照触发器定时自动运行没有停止日期的吗

**Comment by XiaoMiku01** [comment]
是的，反正不要钱，需要改的时候再自己去改就行了

**Comment by AmakuraMio0017** [comment]
> 是的，反正不要钱

收到，谢谢
幸苦了
