### ISSUE TITLE
请问下为啥我在源码里去掉了大于21级就不送小心心的判断，但运行起来还是给我提示这个log呢

### ISSUE THREAD

**Issue by wmkai** [XiaoMiku01/bili-live-heart#50]
喜欢的主播已经20级了，但还是想每天送一下，所以我去掉了判断语句，但log还是提示我大于21级不赠送

**Comment by XiaoMiku01** [comment]
源码中有两处判断了等级，不会修改的话还是建议不要动，你要是真喜欢那位主播，为何不手动赠送呢，这样才更有意义

**Comment by XiaoMiku01** [comment]
block了，下次相同问题不要多开iss,谢谢
