### ISSUE TITLE
已关注五人，但请求被拦截

### ISSUE THREAD

**Issue by IDarkBoss** [XiaoMiku01/bili-live-heart#52]
![image](https://user-images.githubusercontent.com/26338127/162867823-8fa11489-f1c4-4f45-b9d5-9b57c80f1bce.png)
![image](https://user-images.githubusercontent.com/26338127/162867846-207fbf1b-4dc8-4246-b255-b89654707cce.png)
<br/>
- 腾讯云函数python3.6，1.2.1版本
- 云函数1.2.0版运行是正常
- git拉到本地运行，运行也正常

**Comment by LMWC** [comment]
你每天运行两次就可以了，我今天也出现了这个问题

**Comment by XiaoMiku01** [comment]
这是B站拦截的。尝试多运行几次吧，我有空将时间间隔改为3秒吧
