### ISSUE TITLE
#文档建议 获取Cookie的方式

### ISSUE THREAD

**Issue by ZiuChen** [XiaoMiku01/bili-live-heart#54]
从另一个bilibili的工具看到的，可以直接访问[这个网址](https://api.bilibili.com/x/web-interface/nav)
在F12中可以更清晰的获得cookie
![image](https://user-images.githubusercontent.com/64892985/163296734-ef92f320-cae3-4ef0-8cd5-b0683cf892f0.png)

**Comment by XiaoMiku01** [comment]
这是原来的cookie获取方式，由于很多人的浏览器环境不同导致会缺少关键字段，所以我有手写了新的cookie获取器，更加方便不易出错
