### ISSUE TITLE
b站获取小心心规则已改版

### ISSUE THREAD

**Issue by smyhm** [XiaoMiku01/bili-live-heart#56]
如图
![WechatIMG135893](https://user-images.githubusercontent.com/101782263/168839555-730b42dd-132b-4e7a-b6db-6849c43981b2.jpeg)

**Comment by guyouhantan** [comment]
叔叔真的sm了

**Comment by yyf0910** [comment]
确实

**Comment by Healock** [comment]
这改了真莫名其妙的，叔叔biss

**Comment by ABlackx** [comment]
叔叔真的是

**Comment by XiaoMiku01** [comment]
https://github.com/XiaoMiku01/fansMedalHelper 新版
