### ISSUE TITLE
"errorMessage":"Invoking task timed out after 900 seconds"

### ISSUE THREAD

**Issue by GunBusterMichael** [XiaoMiku01/bili-live-heart#6]
ERROR RequestId:37b82f81-66b5-4011-8584-c39b2f1c376e Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 900 seconds","statusCode":433}

END RequestId:37b82f81-66b5-4011-8584-c39b2f1c376e

Report RequestId:37b82f81-66b5-4011-8584-c39b2f1c376e Duration:900000ms Memory:128MB MemUsage:30.363281MB
第十四个小心心发送成功，提示 60秒后发送第15个22479365号直播间内心跳 后显示上述错误提示

**Comment by XiaoMiku01** [comment]
粉丝牌小于12个会时间不够

**Comment by GunBusterMichael** [comment]
> 

我的粉丝牌正好12个

**Comment by XiaoMiku01** [comment]
可能有的粉丝牌是无效直播间或者没有直播间

**Comment by GunBusterMichael** [comment]
> 

好的好的。那报这种错，程序还是否可以给牌子升等级呀

**Comment by XiaoMiku01** [comment]
不会，只能获得24个小心心，因为时间不够打卡赠送了

**Comment by GunBusterMichael** [comment]
> 不会，只能获得24个小心心，因为时间不够打卡赠送了

收到，谢谢😘
