### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chenxi492** [XiaoMiku01/bili-live-heart#7]
START RequestId:204ae56c-35b9-41a4-b903-8b0098510d43
start!
Using selector: EpollSelector
运行出错:KeyError('LIVE_BUVID',)
Response RequestId:204ae56c-35b9-41a4-b903-8b0098510d43 RetMsg:false
END RequestId:204ae56c-35b9-41a4-b903-8b0098510d43
Report RequestId:204ae56c-35b9-41a4-b903-8b0098510d43 Duration:193ms Memory:128MB MemUsage:62.835938MB
怎么会事呢泪目了www

**Comment by XiaoMiku01** [comment]
重新抓cookie
