### ISSUE TITLE
每日首次打卡无法拿满小心心

### ISSUE THREAD

**Issue by chenyl0426** [XiaoMiku01/bili-live-heart#8]
有16个牌子，可以运行到直播间打卡、投喂和方糖推送，运行一次的时间跟之前差不多（10分钟左右），但是这几天都不能拿满小心心了
![Stitch_20211206_065721](https://user-images.githubusercontent.com/61819463/144767353-8262449b-3d93-46d1-8d76-bdf93f99c1fe.png)

**Comment by chenyl0426** [comment]
日志是这个样子的……
![IMG_20211206_070053_Mosaic_7_0_57](https://user-images.githubusercontent.com/61819463/144767531-8073f3d4-7e0a-4b6e-93d9-ecead98c333f.jpg)

**Comment by XiaoMiku01** [comment]
我的也遇到相同状况，原因未知，可能是和触发时间有关

**Comment by chenyl0426** [comment]
> 我的也遇到相同状况，原因未知，可能是和触发时间有关

我今天上控制台把触发器改了早上6点定时触发，明天再观察一下情况

**Comment by chenyl0426** [comment]
> 我的也遇到相同状况，原因未知，可能是和触发时间有关

设了6点，能打满了，明天再观察
![IMG_20211207_114738](https://user-images.githubusercontent.com/61819463/144962673-f16ae005-e90e-4376-82fd-ed795b7cce6f.jpg)
